version: '2'

volumes:
  site-mysql-v1:
  nfsmountCC:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=172.16.1.55,rw"      # IP of nfs server.  This is also where you put any options '-o' in standard option format
      device: ":/mnt/site1/bitrix"
services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
    - '80:80'
    links:
    - php74-fpm:php
    networks:
    - site
    volumes:
    - ./logs/nginx:/var/log/nginx
    - ./var/www/site.ru:/var/www/site.ru
    - nfsmountCC:/var/www/site.ru/bitrix:ro
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
  php74-fpm:
    build: ./php74-fpm
    container_name: php74-fpm
    ports:
    - '9000:9000'
    links:
    - mysql
    - memcached
    networks:
    - site
    volumes:
    - ./var/www/site.ru:/var/www/site.ru
    - nfsmountCC:/var/www/site.ru/bitrix:ro
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
  php74-cli:
    build: ./php74-cli
    container_name: php74-cli
    links:
    - mysql
    - memcached
    networks:
    - site
    volumes:
    - ./var/www/site.ru:/var/www/site.ru
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
  mysql:
    build: ./mysql
    container_name: mysql
    ports:
    - '3306:3306'
    environment:
      MYSQL_DATABASE: site
      MYSQL_USER: site
      MYSQL_PASSWORD: xV1S1YQFLwL1
      MYSQL_ROOT_PASSWORD: ZVjS2YQaL6L1
    networks:
    - site
    volumes:
    - site-mysql-v1:/var/lib/mysql
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
  memcached:
    image: memcached:1.5-alpine
    container_name: memcached
    ports:
    - '11211:11211'
    entrypoint:
    - memcached
    - --memory-limit=1024m
    - --max-item-size=32m
    restart: unless-stopped
    mem_limit: 1073741824
    cpu_shares: 512
networks:
  site:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.0.0/8